{{- if and .Values.ap.redis.enabled .Values.ap.redis.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "async-processor.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "async-processor.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.ap.redis.url | quote }}
{{- end }}
